// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUpTbdBmHiztEQY6O5WxIhl2bk6PcV5Vw',
    appId: '1:637530699136:android:fb7d78e5bb33fac5243d65',
    messagingSenderId: '637530699136',
    projectId: 'bandiwala-2025',
    databaseURL: 'https://bandiwala-2025-default-rtdb.firebaseio.com',
    storageBucket: 'bandiwala-2025.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEQ7FUCHGq5YWpHNrgNexv5nOz3CsFh1E',
    appId: '1:637530699136:web:61abbb7c9acfb1da243d65',
    messagingSenderId: '637530699136',
    projectId: 'bandiwala-2025',
    authDomain: 'bandiwala-2025.firebaseapp.com',
    databaseURL: 'https://bandiwala-2025-default-rtdb.firebaseio.com',
    storageBucket: 'bandiwala-2025.firebasestorage.app',
    measurementId: 'G-ZP8KGTHP6E',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNko1PrMK-r2b1Kd8kkMok7nMK8X-hw6E',
    appId: '1:637530699136:ios:05e74c2d84e3708a243d65',
    messagingSenderId: '637530699136',
    projectId: 'bandiwala-2025',
    databaseURL: 'https://bandiwala-2025-default-rtdb.firebaseio.com',
    storageBucket: 'bandiwala-2025.firebasestorage.app',
    iosClientId: '637530699136-hrnhh42il334sni1k9njsrjbch9b1b4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthFirebaseTutorial',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNko1PrMK-r2b1Kd8kkMok7nMK8X-hw6E',
    appId: '1:637530699136:ios:05e74c2d84e3708a243d65',
    messagingSenderId: '637530699136',
    projectId: 'bandiwala-2025',
    databaseURL: 'https://bandiwala-2025-default-rtdb.firebaseio.com',
    storageBucket: 'bandiwala-2025.firebasestorage.app',
    iosClientId: '637530699136-hrnhh42il334sni1k9njsrjbch9b1b4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthFirebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEQ7FUCHGq5YWpHNrgNexv5nOz3CsFh1E',
    appId: '1:637530699136:web:b1a79341bd6cab81243d65',
    messagingSenderId: '637530699136',
    projectId: 'bandiwala-2025',
    authDomain: 'bandiwala-2025.firebaseapp.com',
    databaseURL: 'https://bandiwala-2025-default-rtdb.firebaseio.com',
    storageBucket: 'bandiwala-2025.firebasestorage.app',
    measurementId: 'G-GRR630PY7F',
  );

}